Tooltip component: first version
fyndiq/fyndiq-ui pull request #9
Opened 2017-04-21 13:19 UTC by thibautRe

<img width="101" alt="screen shot 2017-04-21 at 15 18 27" src="https://cloud.githubusercontent.com/assets/1416801/25279130/cae40406-26a5-11e7-9bc7-e0c67ce4b984.png" align="right">

## Overview

Adds a tooltip component

2017-05-24 15:35 UTC, Dildaarkhan requested changes
Module Not found Error

2017-05-24 16:56 UTC, thibautRe commented
Sorry I forgot to add some How to test steps, I fixed it

2017-05-26 06:32 UTC, Dildaarkhan approved these changes

2017-05-26 06:33 UTC, Dildaarkhan approved these changes

2017-05-26 07:46 UTC, merged